modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://strictgaming.com/support"
showAsResourcePack=false

[[mods]]
  modId="eliteholograms"
  version="1.21.1-1.0.0"
  displayName="Elite Holograms"
  displayURL="https://strictgaming.com"
  credits="StrictGaming"
  authors="EliteScouter"
  description='''
  A powerful hologram mod for Minecraft NeoForge
  '''

  [[dependencies.eliteholograms]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.eliteholograms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH" 